-- ============================================================
-- Black Horse Beamish — Checklists / Accident Reports / Documents
-- Same Supabase project as the till. Anon publishable key is the
-- only credential the two web apps use, so RLS policies here are
-- permissive (anon can do everything) — matching the till_* tables.
-- Idempotent: safe to re-run.
-- ============================================================

create extension if not exists pgcrypto;

-- ---------------- checklist templates & questions ----------------
create table if not exists public.checklist_templates (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in ('guest_journey','shift','health_safety')),
  area text not null,                 -- 'Bar' | 'Kitchen' | 'Front of House' | 'Whole venue' | 'Fire Safety' ...
  name text not null,
  frequency text not null check (frequency in ('daily','weekly','monthly','six_monthly','annual')),
  due_time time not null default '23:59',
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.checklist_items (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null references public.checklist_templates(id) on delete cascade,
  sort_order int not null default 0,
  prompt text not null,
  input_type text not null default 'yes_no' check (input_type in ('yes_no','text','number','temperature','photo')),
  help_text text,
  required boolean not null default true,
  pass_min numeric,
  pass_max numeric,
  active boolean not null default true
);

-- one row per period the checklist becomes due (e.g. one per day for 'daily')
create table if not exists public.checklist_runs (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null references public.checklist_templates(id) on delete cascade,
  period_key text not null,           -- '2026-09-19' | '2026-W38' | '2026-09' | '2026-H2' | '2026'
  due_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending','completed','missed')),
  completed_by text,
  completed_at timestamptz,
  signature_url text,
  notes text,
  created_at timestamptz not null default now(),
  unique(template_id, period_key)
);

create table if not exists public.checklist_answers (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.checklist_runs(id) on delete cascade,
  item_id uuid not null references public.checklist_items(id) on delete cascade,
  value text,
  flagged boolean not null default false,
  photo_url text,
  created_at timestamptz not null default now(),
  unique(run_id, item_id)
);

-- ---------------- accident / incident reports ----------------
create table if not exists public.accident_reports (
  id uuid primary key default gen_random_uuid(),
  ref_no bigint generated by default as identity,
  reported_by text not null,
  reported_at timestamptz not null default now(),
  incident_at timestamptz not null,
  location text not null,
  injured_name text not null,
  injured_type text not null check (injured_type in ('staff','guest','contractor','other')),
  injured_contact text,
  what_happened text not null,
  injury_description text,
  body_part text,
  first_aid_given boolean not null default false,
  first_aider_name text,
  treatment_given text,
  went_to_hospital boolean not null default false,
  witnesses text,
  cause text,
  actions_taken text,
  riddor_reportable boolean not null default false,
  riddor_category text check (riddor_category in ('death','specified_injury','over_7_day','occupational_disease','dangerous_occurrence') or riddor_category is null),
  reported_to_hse boolean not null default false,
  hse_reference text,
  photo_urls jsonb not null default '[]',
  signature_url text,
  status text not null default 'open' check (status in ('open','reviewed','closed')),
  created_at timestamptz not null default now()
);

-- ---------------- compliance document library ----------------
create table if not exists public.compliance_documents (
  id uuid primary key default gen_random_uuid(),
  category text not null,             -- 'Fire Alarm Service' | 'Fixed Wire Testing (EICR)' | 'PAT Testing' | ...
  title text not null,
  file_url text not null,
  file_name text,
  issued_date date,
  expiry_date date,
  uploaded_by text,
  uploaded_at timestamptz not null default now(),
  notes text
);

create index if not exists idx_checklist_runs_template on public.checklist_runs(template_id);
create index if not exists idx_checklist_runs_status on public.checklist_runs(status);
create index if not exists idx_checklist_items_template on public.checklist_items(template_id);
create index if not exists idx_checklist_answers_run on public.checklist_answers(run_id);
create index if not exists idx_accident_reports_at on public.accident_reports(incident_at);
create index if not exists idx_compliance_docs_expiry on public.compliance_documents(expiry_date);

-- ---------------- RLS: anon publishable key does everything ----------------
alter table public.checklist_templates enable row level security;
alter table public.checklist_items enable row level security;
alter table public.checklist_runs enable row level security;
alter table public.checklist_answers enable row level security;
alter table public.accident_reports enable row level security;
alter table public.compliance_documents enable row level security;

do $pol$
declare t text;
begin
  foreach t in array array['checklist_templates','checklist_items','checklist_runs',
                            'checklist_answers','accident_reports','compliance_documents']
  loop
    execute format('drop policy if exists anon_all on public.%I', t);
    execute format('create policy anon_all on public.%I for all using (true) with check (true)', t);
  end loop;
end
$pol$;
